COHORT AND FUNNEL ANALYSIS

EDA DATA CLEANING AND DATA PREPROCCESSING

In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('Assignment Datasets Funnel Cohort.csv')
df.head()

C:\Users\m s i\AppData\Local\Temp\ipykernel_22628\2496724379.py:1: DtypeWarning: Columns (3,4,5) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('Assignment Datasets Funnel Cohort.csv')

,event_id,user_id,age,gender,city,country,session_id,sequence_number,created_at,browser,traffic_source,event_type
0,555311,42922.0,46.0,M,Bogatynia,Poland,f65f7f3f-1078-45da-a7af-2dd41a894e5d,3,2023-01-19 22:54:38 UTC,Other,Email,cart
1,714816,55343.0,16.0,M,Bogatynia,Poland,cc3509fc-641b-4632-aca7-4949209b9afb,4,2023-11-26 17:12:19 UTC,Safari,Email,cart
2,464405,35775.0,46.0,F,Bogatynia,Poland,16f8b065-9b2e-47bf-b8e7-793060cfbe04,9,2023-09-27 02:46:04 UTC,Firefox,Adwords,cart
3,649908,50243.0,47.0,M,Bogatynia,Poland,8b145bdf-4ddd-473a-8095-c35504afa112,3,2023-04-16 08:50:42 UTC,Chrome,Adwords,cart
4,874098,67437.0,30.0,M,Zgorzelec,Poland,4871ce1f-0b5c-446d-aa7c-016c959cbe56,3,2023-05-18 04:24:49 UTC,Firefox,Email,cart

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 418279 entries, 0 to 418278
Data columns (total 12 columns):
 #   Column           Non-Null Count   Dtype
---  ------           --------------   -----
 0   event_id         418279 non-null  int64
 1   user_id          265687 non-null  float64
 2   age              265687 non-null  float64
 3   gender           265687 non-null  object
 4   city             262839 non-null  object
 5   country          265687 non-null  object
 6   session_id       418279 non-null  object
 7   sequence_number  418279 non-null  int64
 8   created_at       418279 non-null  object
 9   browser          418279 non-null  object
 10  traffic_source   418279 non-null  object
 11  event_type       418279 non-null  object
dtypes: float64(2), int64(2), object(8)
memory usage: 38.3+ MB

In [4]:
df_2 = pd.read_csv('Assignment Datasets Funnel Cohort Sales.csv')
df_2.head()

,order_id,order_date,user_id,user_name,age,gender,product_id,product_name,category,quantity,sale_price,cost
0,102234,2024-10-22,81494,Sheri Ramos,31,F,8038,Embroidered Capri Set - Sizes: 1X2X3X4X,Clothing Sets,1,"22,98999977","13,86296978"
1,72773,2024-03-02,57833,Judy Beltran,56,F,8032,Aeropostale Womens; Juniors Long Sleeve Logo G...,Clothing Sets,1,"34,5","21,01049991"
2,123719,2024-03-01,98736,Erin Mora,55,F,8030,Calvin Klein Women's MSY Velour Pant,Clothing Sets,1,50,"32,8999998"
3,14065,2024-05-22,11186,Shelly Hill,25,F,8027,Only Necessities Plus Size Peachskin 3 piece P...,Clothing Sets,1,"54,99000168","35,79849092"
4,37640,2024-10-07,29909,Tina Davis,26,F,8049,VIOLET BLOUSE GAUCHO PALAZZO SET ASYM - FITS (...,Clothing Sets,1,"57,99000168","34,09812074"

In [5]:
df_2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 19163 entries, 0 to 19162
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   order_id      19163 non-null  int64
 1   order_date    19163 non-null  object
 2   user_id       19163 non-null  int64
 3   user_name     19163 non-null  object
 4   age           19163 non-null  int64
 5   gender        19163 non-null  object
 6   product_id    19163 non-null  int64
 7   product_name  19162 non-null  object
 8   category      19163 non-null  object
 9   quantity      19163 non-null  int64
 10  sale_price    19163 non-null  object
 11  cost          19163 non-null  object
dtypes: int64(5), object(7)
memory usage: 1.8+ MB

In [6]:
df['user_id'].nunique()

28969

In [7]:
df_2['user_id'].nunique()

12293

COHORT EDA CLEANING AND PREPROCCESSING

In [8]:
df['user_id'] = df['user_id'].astype('Int64') # 'int64' Error Menghadapi Nan Values, Gunakan 'Int64'.
df['age'] = df['age'].astype('Int64')
df['created_at'] = pd.to_datetime(df['created_at'])

“We used Pandas nullable integer (Int64) to preserve missing user identifiers without introducing artificial values.”

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 418279 entries, 0 to 418278
Data columns (total 12 columns):
 #   Column           Non-Null Count   Dtype
---  ------           --------------   -----
 0   event_id         418279 non-null  int64
 1   user_id          265687 non-null  Int64
 2   age              265687 non-null  Int64
 3   gender           265687 non-null  object
 4   city             262839 non-null  object
 5   country          265687 non-null  object
 6   session_id       418279 non-null  object
 7   sequence_number  418279 non-null  int64
 8   created_at       418279 non-null  datetime64[ns, UTC]
 9   browser          418279 non-null  object
 10  traffic_source   418279 non-null  object
 11  event_type       418279 non-null  object
dtypes: Int64(2), datetime64[ns, UTC](1), int64(2), object(7)
memory usage: 39.1+ MB

In [10]:
df.isna().sum()

event_id                0
user_id            152592
age                152592
gender             152592
city               155440
country            152592
session_id              0
sequence_number         0
created_at              0
browser                 0
traffic_source          0
event_type              0
dtype: int64

Why are there so many Nans? This is normal in e-commerce and product data
because there may be many anonymous visitors, tracking before 
user registration, page views without logging in.

In [11]:
df_cohort = df[df['user_id'].notna()].copy()

“Cohort analysis was only performed on instances with a valid user_id. Other demographic attributes were not filtered, as they are not required for retention calculations. Filtering these attributes based on user_id would unnecessarily reduce the data set, as it would eliminate user_ids that do not have complete demographic attributes.

In [12]:
df_cohort.info()

<class 'pandas.core.frame.DataFrame'>
Index: 265687 entries, 0 to 418278
Data columns (total 12 columns):
 #   Column           Non-Null Count   Dtype
---  ------           --------------   -----
 0   event_id         265687 non-null  int64
 1   user_id          265687 non-null  Int64
 2   age              265687 non-null  Int64
 3   gender           265687 non-null  object
 4   city             262839 non-null  object
 5   country          265687 non-null  object
 6   session_id       265687 non-null  object
 7   sequence_number  265687 non-null  int64
 8   created_at       265687 non-null  datetime64[ns, UTC]
 9   browser          265687 non-null  object
 10  traffic_source   265687 non-null  object
 11  event_type       265687 non-null  object
dtypes: Int64(2), datetime64[ns, UTC](1), int64(2), object(7)
memory usage: 26.9+ MB

In [13]:
df_cohort.isna().sum()

event_id              0
user_id               0
age                   0
gender                0
city               2848
country               0
session_id            0
sequence_number       0
created_at            0
browser               0
traffic_source        0
event_type            0
dtype: int64

In [14]:
df_cohort['city_segment'] = df_cohort['city'].fillna('Uknown')

In [15]:
df_cohort.info()

<class 'pandas.core.frame.DataFrame'>
Index: 265687 entries, 0 to 418278
Data columns (total 13 columns):
 #   Column           Non-Null Count   Dtype
---  ------           --------------   -----
 0   event_id         265687 non-null  int64
 1   user_id          265687 non-null  Int64
 2   age              265687 non-null  Int64
 3   gender           265687 non-null  object
 4   city             262839 non-null  object
 5   country          265687 non-null  object
 6   session_id       265687 non-null  object
 7   sequence_number  265687 non-null  int64
 8   created_at       265687 non-null  datetime64[ns, UTC]
 9   browser          265687 non-null  object
 10  traffic_source   265687 non-null  object
 11  event_type       265687 non-null  object
 12  city_segment     265687 non-null  object
dtypes: Int64(2), datetime64[ns, UTC](1), int64(2), object(8)
memory usage: 28.9+ MB

In [16]:
df_cohort.isna().sum()

event_id              0
user_id               0
age                   0
gender                0
city               2848
country               0
session_id            0
sequence_number       0
created_at            0
browser               0
traffic_source        0
event_type            0
city_segment          0
dtype: int64

In [17]:
df_cohort.duplicated().sum()

np.int64(0)

In [18]:
df_cohort.nunique()

event_id           265687
user_id             28969
age                    59
gender                  2
city                 5619
country                14
session_id          50349
sequence_number        13
created_at         263512
browser                 5
traffic_source          5
event_type              4
city_segment         5620
dtype: int64

In [19]:
df_cohort.describe(include='all')

,event_id,user_id,age,gender,city,country,session_id,sequence_number,created_at,browser,traffic_source,event_type,city_segment
count,2.656870e+05,265687.0,265687.0,265687,262839,265687,265687,265687.000000,265687,265687,265687,265687,265687
unique,NaN,<NA>,<NA>,2,5619,14,50349,NaN,NaN,5,5,4,5620
top,NaN,<NA>,<NA>,F,Shanghai,China,e407c613-3685-4079-83e1-2d450a1f6fa4,NaN,NaN,Chrome,Email,cart,Shanghai
freq,NaN,<NA>,<NA>,134682,6732,88907,9,NaN,NaN,132367,120327,95634,6732
mean,6.471929e+05,49931.155348,41.025319,NaN,NaN,NaN,NaN,5.054466,2023-07-19 15:01:26.514861056+00:00,NaN,NaN,NaN,NaN
min,1.600000e+01,2.0,12.0,NaN,NaN,NaN,NaN,1.000000,2023-01-01 00:01:41+00:00,NaN,NaN,NaN,NaN
25%,3.223325e+05,24718.0,26.0,NaN,NaN,NaN,NaN,3.000000,2023-04-21 23:30:56.500000+00:00,NaN,NaN,NaN,NaN
50%,6.475590e+05,50062.0,41.0,NaN,NaN,NaN,NaN,5.000000,2023-07-28 12:28:35+00:00,NaN,NaN,NaN,NaN
75%,9.726035e+05,75007.0,56.0,NaN,NaN,NaN,NaN,6.000000,2023-10-20 13:46:40.500000+00:00,NaN,NaN,NaN,NaN
max,1.296336e+06,99999.0,70.0,NaN,NaN,NaN,NaN,13.000000,2023-12-31 23:59:53+00:00,NaN,NaN,NaN,NaN
std,3.748897e+05,29001.961975,17.092576,NaN,NaN,NaN,NaN,3.017551,NaN,NaN,NaN,NaN,NaN

COHORT CREATION FOR COHORT ANALYSIS

A cohort is a group of individuals who share certain common characteristics or experiences (such as birth year, disease, or exposure) and are followed over time to study changes or outcomes. It is often used in medical research (cohort studies), social sciences, and business analysis (cohort analysis) to understand generational behavior or trends. The term originates from ancient Roman military units and is also similar to the concept of "generations" or age groups.

5️⃣ Why are both MUST be present?

Because the cohort index = the time interval between these two events.

cohort_index = activity_month - cohort_month

In human language:

“How many months after the user joined did this event occur?”

FIRST ACTIVITY DATE PER USER (MUST HAVE) : 

1. Determine How Many Active Users Are Per First Event : 

This is the Foundation of Cohorts, Without This Cohorts Cannot Be Created

In [20]:
first_activity = (df_cohort.groupby('user_id')['created_at']
                  .min().reset_index()
                  .rename(columns={'created_at':'first_activity_date'}))

2. Create Cohort Based On Month - Usually Cohort Based On Month, So Now Every User_Id Are Recorded Based On Month From Their First Activity Event.

In [21]:
first_activity['cohort_month'] = (first_activity['first_activity_date'].
                                  dt.to_period('M'))

C:\Users\m s i\AppData\Local\Temp\ipykernel_22628\2877543924.py:2: UserWarning: Converting to PeriodArray/Index representation will drop timezone information.
  dt.to_period('M'))

3. Combine These Data first_activity To df_cohort

Reason Is We Want To See Later How Many User Per Event After First Event To The Last Event, 
In Other Words, We Want To See How Many User Based On the process of developing events per event after the first event.

In [22]:
df_cohort = df_cohort.merge(first_activity[['user_id', 'cohort_month']],
                            on='user_id', how='left')

4. Create Activity Month. 

We Already Created Cohort Month When User Started Active Per-First Event, Now We Create How Many User Active Per Month Event.

In [23]:
df_cohort['activity_month'] = df_cohort['created_at'].dt.to_period('M')

C:\Users\m s i\AppData\Local\Temp\ipykernel_22628\2650963868.py:1: UserWarning: Converting to PeriodArray/Index representation will drop timezone information.
  df_cohort['activity_month'] = df_cohort['created_at'].dt.to_period('M')

5. Create For Calculating Cohort Index. 

The Logic Is Like These Event Happen In Which Month Since User Joined The Event. These Calculation Representing Mathematic Logic Between Year And Logic For Calculating the distance between active events per user and the user's activity towards a particular event.

In [26]:
df_cohort['cohort_index'] = ((df_cohort['created_at'].dt.year - df_cohort['cohort_month'].dt.year)
                             * 12  + (df_cohort['created_at'].dt.month - df_cohort['cohort_month'].dt.month))

6. Create Retention User Table

These Code For Calculating Unique User_Id Per Event And First Activity Event, So It Will Not Duplicate, Because User_Id Can Have Many Event But The Point Is Not Calculate That, But To Calculate Every User Who Come Back Over And Over, Or In Other Words Calculate Every Unique User_Id In Every Event Since First Activity Event For Retention Valuation.

In [27]:
cohort_table = (df_cohort.groupby(
    ['cohort_month','cohort_index'])['user_id'].
    nunique().reset_index()
)

In [37]:
cohort_table.head()

  cohort_month  cohort_index  user_id
0      2023-01             0     2246
1      2023-01             1      138
2      2023-01             2       75
3      2023-01             3       63
4      2023-01             4       66

7. Create Cohort Pivot Table

These Code For Make It Easier Later For Calculating Retention Rate.

In [28]:
cohort_pivot = cohort_table.pivot(
    index='cohort_month',
    columns='cohort_index',
    values='user_id'
)
cohort_size = cohort_pivot.iloc[:,0] # TAKE ALL FIRST ROW AND COLUMN AT INDEX 0

8. Create Retention Rate Using Divide With Cohort Size Per Every Row In cohort_pivot. axis = 0 means the row movement is down per column, whereas if axis = 1 means the movement is sliding per row.

In [29]:
retention_rate = cohort_pivot.divide(cohort_size, axis=0)

“To maintain logical consistency, analysis reproducibility, and separate the analytical process from the visualization.” I used this retention data and then used it to visualize cohort analysis in Tableau.

9. Create Long Format For Retention Rate Cohort Analysis For New File CSV FORMAT To Visualize Cohort Analysis With tableau

The structure may be different, but the meaning of the data remains unchanged.

The only changes are:

A. storage method

B. tool readability

📌 Information contained = IDENTICAL

WHY IS COLLABORATE_PIVOT IN PYTHON?

Because HUMANS THINK IN MATRIXES when analyzing:

1. Compare rows

2. Look for patterns to the right

3. Detect drop-offs

👉 That's the ANALYSIS phase

WHY DOES TABLEAU REQUIRE LONG FORMAT?

Because the visualization engine thinks in records.

Tableau works like this:

“Each row = one visual point.”

Global data science and BI rules

Called:

A. tidy data

B. normalized format

C. long format

In [30]:
retention_long = (retention_rate.reset_index().
                  melt(id_vars='cohort_month',
                       var_name='cohort_index',
                       value_name='retention_rate'))

In [31]:
retention_long.to_csv('cohort_retention_tableau.csv',index=False)

Checking The New File For Cohort Analysis.

In [35]:
df_retentioncohort = pd.read_csv('cohort_retention_tableau.csv')
df_retentioncohort.head(25)

   cohort_month  cohort_index  retention_rate
0       2023-01             0        1.000000
1       2023-02             0        1.000000
2       2023-03             0        1.000000
3       2023-04             0        1.000000
4       2023-05             0        1.000000
5       2023-06             0        1.000000
6       2023-07             0        1.000000
7       2023-08             0        1.000000
8       2023-09             0        1.000000
9       2023-10             0        1.000000
10      2023-11             0        1.000000
11      2023-12             0        1.000000
12      2023-01             1        0.061443
13      2023-02             1        0.069249
14      2023-03             1        0.071615
15      2023-04             1        0.067158
16      2023-05             1        0.061551
17      2023-06             1        0.068241
18      2023-07             1        0.061814
19      2023-08             1        0.063241
20      2023-09             1        0.072837
21      2023-10             1        0.081617
22      2023-11             1        0.076037
23      2023-12             1             NaN
24      2023-01             2        0.033393

FUNNEL ANALYSIS EDA

In [39]:
df_2.head()

,order_id,order_date,user_id,user_name,age,gender,product_id,product_name,category,quantity,sale_price,cost
0,102234,2024-10-22,81494,Sheri Ramos,31,F,8038,Embroidered Capri Set - Sizes: 1X2X3X4X,Clothing Sets,1,"22,98999977","13,86296978"
1,72773,2024-03-02,57833,Judy Beltran,56,F,8032,Aeropostale Womens; Juniors Long Sleeve Logo G...,Clothing Sets,1,"34,5","21,01049991"
2,123719,2024-03-01,98736,Erin Mora,55,F,8030,Calvin Klein Women's MSY Velour Pant,Clothing Sets,1,50,"32,8999998"
3,14065,2024-05-22,11186,Shelly Hill,25,F,8027,Only Necessities Plus Size Peachskin 3 piece P...,Clothing Sets,1,"54,99000168","35,79849092"
4,37640,2024-10-07,29909,Tina Davis,26,F,8049,VIOLET BLOUSE GAUCHO PALAZZO SET ASYM - FITS (...,Clothing Sets,1,"57,99000168","34,09812074"

----------------------------------------------------------------

Here's the conceptual reason why funnels are SEPARATED : 

Reason 1 — The single responsibility dataset principle

In healthy BI:

- Transaction dataset → for operations & revenue

- Funnel dataset → for behavioral conversions

- One dataset = one main question

------------------------------------------------------------------

Reason 2 — Avoiding double counting in Tableau

Tableau:

- It's easy to be "fooled" by repeated data

- If the funnel is in transaction data:

- COUNT, SUM, even LOD can be wrong if not careful

- Mentors usually value clean and defensible funnels, not complex ones.

-----------------------------------------------------------------

Reason 3 — Funnels are summaries by design

Funnels are not exploratory tables, but:

- “Summaries of user journeys”

Philosophically:

- Funnels = processed results

- Transactions = raw materials

Mixing the two often:

- Obscures the story

- Creates ambiguous insights

-----------------------------------------------------------------

----------------------------------------------

FYI : 

- nunique() and COUNT(DISTINCT) are twins that focus on diversity (how many different types there are).

- .value_counts() focuses on distribution/frequency (how often each type appears).

- COUNTIF() is a simple criteria-based tool for spreadsheet environments.

--------------------------------------------

In [40]:
df_2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 19163 entries, 0 to 19162
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   order_id      19163 non-null  int64
 1   order_date    19163 non-null  object
 2   user_id       19163 non-null  int64
 3   user_name     19163 non-null  object
 4   age           19163 non-null  int64
 5   gender        19163 non-null  object
 6   product_id    19163 non-null  int64
 7   product_name  19162 non-null  object
 8   category      19163 non-null  object
 9   quantity      19163 non-null  int64
 10  sale_price    19163 non-null  object
 11  cost          19163 non-null  object
dtypes: int64(5), object(7)
memory usage: 1.8+ MB

In [41]:
df_2.describe(include='all')

,order_id,order_date,user_id,user_name,age,gender,product_id,product_name,category,quantity,sale_price,cost
count,19163.000000,19163,19163.000000,19163,19163.000000,19163,19163.000000,19162,19163,19163.0,19163,19163
unique,NaN,366,NaN,11303,NaN,2,NaN,13533,26,NaN,2739,13215
top,NaN,2024-12-29,NaN,Robert Smith,NaN,M,NaN,Wrangler Men's Premium Performance Cowboy Cut ...,Intimates,NaN,25,"12,98"
freq,NaN,114,NaN,15,NaN,9667,NaN,12,1370,NaN,717,8
mean,63115.468455,NaN,50234.590617,NaN,41.215624,NaN,15305.692585,NaN,NaN,1.0,NaN,NaN
std,36335.649328,NaN,28984.285353,NaN,17.112735,NaN,8425.189694,NaN,NaN,0.0,NaN,NaN
min,5.000000,NaN,3.000000,NaN,12.000000,NaN,1.000000,NaN,NaN,1.0,NaN,NaN
25%,31572.000000,NaN,25133.000000,NaN,26.000000,NaN,8044.000000,NaN,NaN,1.0,NaN,NaN
50%,63735.000000,NaN,50599.000000,NaN,41.000000,NaN,16095.000000,NaN,NaN,1.0,NaN,NaN
75%,94477.000000,NaN,75259.000000,NaN,56.000000,NaN,22625.000000,NaN,NaN,1.0,NaN,NaN
max,125326.000000,NaN,99987.000000,NaN,70.000000,NaN,29120.000000,NaN,NaN,1.0,NaN,NaN

In [43]:
df_2['order_date'] = pd.to_datetime(df_2['order_date'])

In [44]:
df_2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 19163 entries, 0 to 19162
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   order_id      19163 non-null  int64
 1   order_date    19163 non-null  datetime64[ns]
 2   user_id       19163 non-null  int64
 3   user_name     19163 non-null  object
 4   age           19163 non-null  int64
 5   gender        19163 non-null  object
 6   product_id    19163 non-null  int64
 7   product_name  19162 non-null  object
 8   category      19163 non-null  object
 9   quantity      19163 non-null  int64
 10  sale_price    19163 non-null  object
 11  cost          19163 non-null  object
dtypes: datetime64[ns](1), int64(5), object(6)
memory usage: 1.8+ MB

In [45]:
df_2['sale_price'] = (df_2['sale_price'].astype(str).str.
                      replace(',', '.', regex=False).astype(float))

df_2['cost'] = (df_2['cost'].astype(str).str.replace(',', '.', regex=False).
                astype(float))

In [47]:
df_2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 19163 entries, 0 to 19162
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   order_id      19163 non-null  int64
 1   order_date    19163 non-null  datetime64[ns]
 2   user_id       19163 non-null  int64
 3   user_name     19163 non-null  object
 4   age           19163 non-null  int64
 5   gender        19163 non-null  object
 6   product_id    19163 non-null  int64
 7   product_name  19162 non-null  object
 8   category      19163 non-null  object
 9   quantity      19163 non-null  int64
 10  sale_price    19163 non-null  float64
 11  cost          19163 non-null  float64
dtypes: datetime64[ns](1), float64(2), int64(5), object(4)
memory usage: 1.8+ MB

1. First Step After EDA, We Need To Make Data Aggregation For Profit Analysis Later On.


REVENUE = SALE_PRICE * QUANTITY

TOTAL_COST = QUANTITY * COST

PROFIT  = REVENUE - TOTAL_COST

In [49]:
df_2['revenue'] = df_2['sale_price'] * df_2['quantity']
df_2['total_cost'] = df_2['quantity'] * df_2['cost']
df_2['profit'] = df_2['revenue'] - df_2['total_cost']

2. Build a Funnel (User-Level) Which Means Total Orders Per User.

In [51]:
user_funnel = (df_2.groupby('user_id')['order_id'].
               nunique().reset_index(name='total_orders'))

3. Build A Funnel Stage Based On Category Orders.

In [52]:
def funnel_stage(x):
    if x == 1:
        return '1 Order'
    elif x == 2:
        return '2 Orders'
    else:
        return '3+ Orders'
    

user_funnel['funnel_stage'] = user_funnel['total_orders'].apply(funnel_stage)

4. Build Agreggation Profit Per User Level.

In [53]:
user_profit = (df_2.groupby('user_id')['profit'].
               sum().reset_index(name='total_profit'))

5. Build Data Demographic Based On Demographic Data Existing In This Dataset.

In [54]:
user_demographic = df_2[['user_id', 'user_name', 'age', 'gender']].drop_duplicates()

6. (OPTIONAL) BUILD FOR QUANTITY PER USER LEVEL FOR FURTHER ANALYSIS

In [55]:
user_quantity = (df_2.groupby('user_id')['quantity'].
                 sum().reset_index(name='total_quantity'))

7. (OPTIONAL) BUILD FAVORITE PRODUCT AND CATEGORY PER USER LEVEL BUT NOT DUPLICATE BECAUSE AFTER WE GOT THE FAVORITE FROM THOSE ENTITYS WE DROP THE UNFAVORITE SO IT WILL STAY PER USER LEVEL BUT YOU NEED TO KNOW HOW TO USE IT SO IT WILL NOT MAKE FALSE INSIGHT.

FYI : 

The main function of size() is to return the total number of elements in a Pandas object (DataFrame or Series). Logic & Functionality: The logic is very simple: it counts every data cell present.

- For Series (Single Column): It returns the total number of rows.

- For DataFrame (Table): It returns the total number of cells (rows x columns).

MORE FYI :

Why use .size() in pandas dataframe with groupby because it can count the number of rows in a group that appear how many times, so it is the same as the .value_counts() function only with a wider scope (can be multi-column and more univariate) while in .value_counts() it is the same but is usually more aimed at short EDA and Statistics Because it is Usually For frequency analysis in one column or for global columns.

More FYI :

Drop duplicates can appear because after sort_values ​​it only displays per user level which category / product_name favorite then drops duplicates of the same user_id after its first appearance because sort_values ​​has been done earlier.

In [56]:
user_category = (df_2.groupby(['user_id', 'category']).size().
                 reset_index(name='count'))

favorite_category = (user_category.sort_values(['user_id', 'count'], ascending=False).
                     drop_duplicates('user_id')[['user_id', 'category']].
                     rename(columns={'category':'favorite_category'}))

In [57]:
user_product = (df_2.groupby(['user_id','product_name']).
                            size().reset_index(name='count'))

favorite_product = (user_product.sort_values(['user_id','count'], ascending=False).
                    drop_duplicates('user_id')[['user_id','product_name']].
                    rename(columns={'product_name':'favorite_product'}))

-------------------------------------------

So when you write :

[['user_id','category']]

It does NOT mean:

“I am performing a new analysis”

But:

“I am RESElecting the relevant columns
for my FINAL OUTPUT”

-----------------------------------------------------

Meaning:

- groupby() → new result

- sort_values() → new result

- drop_duplicates() → new result

- [['user_id','category']] → NEW RESULT AGAIN

📌 There is no concept of "late" or "inappropriate" logically as long as:

- the row still exists

- the column still exists

-----------------------------------------------

8. Making New File Dataset With Data Eligible For Funnel Data Analysis And Profiling Data Analysis.

In [58]:
final_funnel_data = (user_funnel.merge(user_profit, on='user_id', how='left').
                     merge(user_quantity, on='user_id', how='left').
                     merge(user_demographic, on='user_id', how='left').
                     merge(favorite_category, on='user_id', how='left').
                     merge(favorite_product, on='user_id', how='left'))

In [59]:
final_funnel_data.head()

,user_id,total_orders,funnel_stage,total_profit,total_quantity,user_name,age,gender,favorite_category,favorite_product
0,3,1,1 Order,23.040000,1,Mark Calhoun,15,M,Underwear,Smartwool Men's Microweight Boxer Brief
1,6,1,1 Order,127.420000,1,Stephen Wagner,70,M,Outerwear & Coats,Volcom Men's Armor Jacket
2,8,1,1 Order,28.944000,1,David Lawrence,56,M,Pants,Timberland Men's Straight Fit Chino Pants
3,38,1,1 Order,8.551140,1,Andrea Freeman,30,F,Blazers & Jackets,Allegra K Ladies Long Sleeve Patch Pockets Ope...
4,50,1,1 Order,203.279999,1,Alexandra Hayes,43,F,Blazers & Jackets,McGinn Women's Clara Textured Blazer

In [61]:
final_funnel_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12293 entries, 0 to 12292
Data columns (total 10 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   user_id            12293 non-null  int64
 1   total_orders       12293 non-null  int64
 2   funnel_stage       12293 non-null  object
 3   total_profit       12293 non-null  float64
 4   total_quantity     12293 non-null  int64
 5   user_name          12293 non-null  object
 6   age                12293 non-null  int64
 7   gender             12293 non-null  object
 8   favorite_category  12293 non-null  object
 9   favorite_product   12293 non-null  object
dtypes: float64(1), int64(4), object(5)
memory usage: 960.5+ KB

In [60]:
final_funnel_data.to_csv('funnel_analysis_ready_for_tableau.csv', index=False)